# Query 1: to produce all the Male Patients with chest pain and the date of onset of the symptom of such patients.


PREFIX ex: <http://www.example.org/btp_ontology/individual/>
PREFIX schema: <http://www.semanticweb.org/btp/clinical/ontology/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?person ?gender ?date_of_onset ?symptom WHERE {
?person a schema:Patient.
?person schema:hasCondition ?indCond.
?person schema:gender "M".
?person schema:gender ?gender.
?indCond a schema:IndividualCondition;
         schema:conditionType ?condition.
?indCond schema:dateOfOnset ?date_of_onset.
?condition rdfs:label "Chest pain".
?condition rdfs:label ?symptom.
}


#Query 2: Get the distinct drugs administered to people with Dyspnea

PREFIX ex: <http://www.example.org/btp_ontology/individual/>
PREFIX schema: <http://www.semanticweb.org/btp/clinical/ontology/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

select ?patient ?drugname where{
    ?patient a schema:Patient.
    ?patient schema:hasCondition ?indCon.
    ?indCond a schema:IndividualCondition;
         schema:conditionType ?condition.
    ?condition rdfs:label "Dyspnea".
    ?patient schema:drug_administered ?indDrug.
    ?indDrug schema:drugType ?drug.
    ?drug rdfs:label ?drugname.
}

#Query 3: Date of Onset of patients with condition snomed id 433736

PREFIX ex: <http://www.example.org/btp_ontology/individual/>
PREFIX schema: <http://www.semanticweb.org/btp/clinical/ontology/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

select (str(?patientId) as ?PatientId) (str(?dateOfOnset) as ?DateOfOnset) ?condition_name where{
    ?patient a schema:Patient;
            schema:hasPatientID ?patientId;
             schema:hasCondition ?indCon.
    ?indCon a schema:IndividualCondition;
              schema:conditionType ?condition.  
    ?indCon schema:dateOfOnset ?dateOfOnset.
    ?condition ?snomed_id ?snomedID.
    ?condition rdfs:label ?condition_name.
FILTER(?snomedID="433736"^^xsd:int).
    
}
limit 200

#Query 4: Routes of drug administration for people with age greater than 60 having fever.
PREFIX ex: <http://www.example.org/btp_ontology/individual/>
PREFIX schema: <http://www.semanticweb.org/btp/clinical/ontology/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

select distinct (str(?method) as ?Method) where{
    ?patient a schema:Patient;
    schema:age ?age.
    ?patient schema:drug_administered ?indDrug;
            schema:hasCondition ?indCon.

    ?indCon schema:conditionType ?condition.
    ?condition rdfs:label "Fever".

    ?indDrug schema:routeOfAdministration ?method.

    Filter (?age>60).
}